### ISSUE TITLE
use composer require in github

### ISSUE THREAD

**Issue by hamidhaghdoost** [jaiwalker/setup-laravel5-package#2]
hi 
I have a project like you say : https://github.com/tuytoosh/simple-admin uploaded with github for windows
now when i want to require it with `composer require tuytoosh/simple-admin` I have this error : 

```
 [InvalidArgumentException]
 Could not find package tuytoosh/simple-admin at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

**Comment by jaiwalker** [comment]
I think this is resolved .
