### ISSUE TITLE
How about package dependency, and package testing.

### ISSUE THREAD

**Issue by antoniputra** [jaiwalker/setup-laravel5-package#4]
So far for your given example its very nice.

but now, how to implement package dependency. for example our package is require other package. how we do that.

lastly and most imprtant, how about testing our package.

thanks.

**Comment by jaiwalker** [comment]
Writing tests  should same  as your app . 
you should treat  package  as app by itself. 
create /tests folder and  composer dev required -  unit test , laravel integrate  package 

But  any ways I will update  package with   test implementation.

**Comment by jaiwalker** [comment]
For using package  Dependency   its simple  But will need a  bit of explanation ... Probarbly  a new .md

**Comment by antoniputra** [comment]
where to create test folder ? in root of laravel framework, or our root package ?

yay..  glad to hear you will update the package with test implementation and dependency. :dancers:  :+1: 

about package dependency I think we can use default laravel composer.json as our package composer. however when our package going to publish, we move the composer.json to our package directory.  (CMIIW)

**Comment by baturorkun** [comment]
hi
Config::get("contact.message")  command access global config file. not read package config file.
So output is "null"

i solved this:
$this->mergeConfigFrom( **DIR**.'/config/contact.php', $this->packageName);
in register() function.  publishes() is dummy now.

**Comment by jaiwalker** [comment]
Hi
 I have  tested this  on  both versions  5.0 and 5.2.37 it  seems to be working .
 while using Publishes() method  you need to run " php artisan vendor:publish "  before you can use the config , yes  you can merge Config like the way  you have  done  it .
