### ISSUE TITLE
Class 'jai\Contact\ContactServiceProvider' not found  

### ISSUE THREAD

**Issue by deepak-kumar** [jaiwalker/setup-laravel5-package#6]
After a fresh git clone and composer install I get following error [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'jai\Contact\ContactServiceProvider' not found

**Comment by jaiwalker** [comment]
I  have tried it, just now with a fresh copy it works fine.
 An issue might be of your namespace  -  run composer dump-autoload and see.
