### ISSUE TITLE
ContactController does not exist

### ISSUE THREAD

**Issue by sevenpointsix** [jaiwalker/setup-laravel5-package#7]
This wouldn't work for me (OS X, Laravel 5.2) until I updated the following line in ContactServiceProvider.php:

`$router->group(['namespace' => 'jai\Contact\Http\Controllers'], function($router)`

to...

`$router->group(['namespace' => 'Jai\Contact\Http\Controllers'], function($router)`

Using the correct case in the namespace fixed it.

**Comment by jaiwalker** [comment]
Thanks I have Update that in new Branch [Include-tests](https://github.com/jaiwalker/setup-laravel5-package/tree/include-tests)
