### ISSUE TITLE
ReflectionException in Route.php line 280: Class jai\Contact\Http\Controllers\ContactController does not exist

### ISSUE THREAD

**Issue by shahidkarimi** [jaiwalker/setup-laravel5-package#8]
ReflectionException in Route.php line 280:
Class jai\Contact\Http\Controllers\ContactController does not exist

**Comment by dineshkaswan5** [comment]
I have also same problem with controller class.

**Comment by jaiwalker** [comment]
I will test it now.
  meanwhile, can you  let me what operating system are you using?

**Comment by dineshkaswan5** [comment]
Thank you for replying, I have problem with my service provider class. now Its Working.

But i can't access views,its shows only contact.php content.how can i use my custom template in laravel.

Can you help me on this.

**Comment by jaiwalker** [comment]
So  just to understand   there was no issue !!!
